name: Tennis Court Booking

on:
  schedule:
    # One-time run on Monday, September 9, 2025 at 8:00 AM EST (13:00 UTC)
    # This will automatically be disabled after it runs
    - cron: '0 13 9 9 1'  # minute hour day month dayofweek (1=Monday)
  workflow_dispatch: # Allow manual triggering
    inputs:
      booking_days:
        description: 'Days ahead to book (e.g., 1 for tomorrow, 2 for day after)'
        required: false
        default: '1'
        type: string

jobs:
  book-tennis-courts:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Chrome and ChromeDriver
      run: |
        # Install Chrome
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
        # ChromeDriver is now included with Chrome for Testing - let's use webdriver-manager
        # The Python webdriver-manager will handle ChromeDriver installation automatically
        
    - name: Show current time
      run: |
        echo "Current EST time: $(TZ=America/New_York date '+%H:%M:%S on %A, %B %d, %Y')"
        if [ "${{ github.event_name }}" = "schedule" ]; then
          echo "🗓️ Scheduled run - starting booking process immediately"
        else
          echo "🔧 Manual trigger - starting booking process"
        fi
      env:
        TZ: America/New_York
        
    - name: Run tennis booking script
      run: |
        # If booking_days is provided, we can modify the booking configuration
        if [ -n "${{ github.event.inputs.booking_days }}" ]; then
          echo "Booking for ${{ github.event.inputs.booking_days }} days ahead"
          # Note: The booking days will be handled by your existing bookings_to_edit.py configuration
        fi
        python3 run_bookings.py
      env:
        # Set timezone to Eastern Time
        TZ: America/New_York
        # Run in headless mode for GitHub Actions
        HEADLESS: true
        # Additional Chrome options for CI environment
        DISPLAY: :99
        # Pass booking days as environment variable
        BOOKING_DAYS: ${{ github.event.inputs.booking_days || '1' }}
        
    - name: Upload booking results (optional)
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: booking-results
        path: |
          *.log
          booking_results.txt
        retention-days: 7